name: CI-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - '*main'
    - '*-ci'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install depencies
        run: |
          sudo apt update
          #sudo apt install debootstrap binfmt-support qemu-user-static

      - uses: actions/download-artifact@v2
        with:
          name: bullseye-chroot

      - name: unpack chroot
        run: |
          sudo tar -xzf debian_bullseye_armhf.tar.gz
          sudo tar -xzf debian_bullseye_arm64.tar.gz

      - name: build hostapd/wpa_supplicant (armhf)
        env:
          ARCH: armhf
          CHROOT: debian_bullseye_armhf
        run: |
          #sudo cp build_hostapd.sh debian_buster_armhf//usr/local/bin/
          #sudo chroot debian_buster_armhf /usr/local/bin/build_hostapd.sh
          sudo cp build_hostapd.sh ${{ env.CHROOT }}//usr/local/bin/
          sudo chroot ${{ env.CHROOT }} /usr/local/bin/build_hostapd.sh
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/hostapd/hostapd ./hostapd_${{ env.ARCH }}
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant ./wpa_supplicant_${{ env.ARCH }}

      - name: build hostapd/wpa_supplicant (arm64)
        env:
          ARCH: armhf
          CHROOT: debian_bullseye_arm64
        run: |
          #sudo cp build_hostapd.sh debian_buster_armhf//usr/local/bin/
          #sudo chroot debian_buster_armhf /usr/local/bin/build_hostapd.sh
          sudo cp build_hostapd.sh ${{ env.CHROOT }}//usr/local/bin/
          sudo chroot ${{ env.CHROOT }} /usr/local/bin/build_hostapd.sh
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/hostapd/hostapd ./hostapd_${{ env.ARCH }}
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant ./wpa_supplicant_${{ env.ARCH }}

      - name: Upload binaries to release
#        if: endsWith(github.ref,'-main') 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          body: ${{ github.sha }}
          tag_name: "CI-BUILD-${{ github.sha }}"
          target_commitish: ${{ github.sha }}
          files: |
             hostapd_*
             wpa_supplicant_*
#            debian_buster_armhf/usr/src/hostapd/hostap/hostapd/hostapd
#            debian_buster_arm64/usr/src/hostapd/hostap/hostapd/hostapd
#            debian_buster_armhf/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant
#            debian_buster_arm64/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant

#      - uses: actions/upload-artifact@v2
#        with:
#          name: binaries
#          path: |
#            debian_buster_armhf/usr/src/hostapd/hostap/hostapd/hostapd
#            debian_buster_arm64/usr/src/hostapd/hostap/hostapd/hostapd
#            debian_buster_armhf/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant
#            debian_buster_arm64/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant
