name: CI-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - '*main'
    - '*-ci'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install depencies
        run: |
          sudo apt update
          sudo apt install binfmt-support qemu-user-static

#      - uses: actions/download-artifact@v2
#        with:
#          name: bullseye-chroot

      - name: setup environment
        env:
          ARCH: armhf
          DEBIAN_RELEASE: buster
          #CHROOT: 'debian_${{ env.DEBIAN_RELEASE }}_${{ env.ARCH }}'
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "DEBIAN_RELEASE=${{ env.DEBIAN_RELEASE }}" >> $GITHUB_ENV
          echo "ARCH=${{ env.ARCH }}" >> $GITHUB_ENV
          #echo "CHROOT=${{ env.CHROOT }}" >> $GITHUB_ENV
          echo "CHROOT=debian_${{ env.DEBIAN_RELEASE }}_${{ env.ARCH }}" >> $GITHUB_ENV

      - name: download and unpack chroot
        run: |
          wget -nv https://github.com/frank-w/arm-crosscompile/releases/download/CHROOT-Bullseye/debian_${{ env.DEBIAN_RELEASE }}_armhf.tar.gz
          wget -nv https://github.com/frank-w/arm-crosscompile/releases/download/CHROOT-Bullseye/debian_${{ env.DEBIAN_RELEASE }}_arm64.tar.gz
          sudo tar -xzf debian_${{ env.DEBIAN_RELEASE }}_armhf.tar.gz --strip-components=5
          sudo tar -xzf debian_${{ env.DEBIAN_RELEASE }}_arm64.tar.gz --strip-components=5
          ls -lh

      - name: build hostapd/wpa_supplicant (armhf)
#        env:
#          ARCH: armhf
#          CHROOT: debian_${{ env.DEBIAN_RELEASE }}_${{ env.ARCH }}
        run: |
          sudo cp build_hostapd.sh ${{ env.CHROOT }}/usr/local/bin/
          sudo chroot ${{ env.CHROOT }} /usr/local/bin/build_hostapd.sh
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/hostapd/hostapd ./hostapd_${{ env.ARCH }}
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant ./wpa_supplicant_${{ env.ARCH }}

      - name: build iproute2 (armhf)
#        env:
#          ARCH: armhf
#          CHROOT: debian_${{ env.DEBIAN_RELEASE }}_armhf
        run: |
          sudo cp build_iproute2.sh ${{ env.CHROOT }}/usr/local/bin/
          sudo chroot ${{ env.CHROOT }} /usr/local/bin/build_iproute2.sh
          cp ${{ env.CHROOT }}/usr/src/iproute2/iproute2.tar.gz ./iproute2_${{ env.ARCH }}.tar.gz


      - name: change arch in environment
        env:
          ARCH: arm64
        run: |
          #echo "ARCH=arm64" >> $GITHUB_ENV
          echo "ARCH=${{ env.ARCH }}" >> $GITHUB_ENV
          echo "CHROOT=debian_${{ env.DEBIAN_RELEASE }}_${{ env.ARCH }}" >> $GITHUB_ENV

      - name: build hostapd/wpa_supplicant (arm64)
#        env:
#          ARCH: arm64
#          CHROOT: debian_${{ env.DEBIAN_RELEASE }}_${{ env.ARCH }}
        run: |
          sudo cp build_hostapd.sh ${{ env.CHROOT }}/usr/local/bin/
          sudo chroot ${{ env.CHROOT }} /usr/local/bin/build_hostapd.sh
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/hostapd/hostapd ./hostapd_${{ env.ARCH }}
          cp ${{ env.CHROOT }}/usr/src/hostapd/hostap/wpa_supplicant/wpa_supplicant ./wpa_supplicant_${{ env.ARCH }}

      - name: build iproute2 (arm64)
#        env:
#          ARCH: arm64
#          CHROOT: debian_${{ env.DEBIAN_RELEASE }}_${{ env.ARCH }}
        run: |
          sudo cp build_iproute2.sh ${{ env.CHROOT }}/usr/local/bin/
          sudo chroot ${{ env.CHROOT }} /usr/local/bin/build_iproute2.sh
          cp ${{ env.CHROOT }}/usr/src/iproute2/iproute2.tar.gz ./iproute2_${{ env.ARCH }}.tar.gz

      - name: Upload binaries to release
#        if: endsWith(github.ref,'-main') 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          body: ${{ github.sha }}
          tag_name: "CI-BUILD-${{ github.sha }}"
          target_commitish: ${{ github.sha }}
          files: |
             hostapd_*
             wpa_supplicant_*
             iproute2_*.tar.gz
