name: TEST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - '*main'
    - '*-ci'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-chroot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install depencies
        run: |
          sudo apt update
          sudo apt install debootstrap binfmt-support qemu-user-static

      - name: build armhf chroot
        run: |
          ./buildchroot.sh armhf

      - name: Install fix for aarch64 ldconfig-issue
        run: |
          sudo add-apt-repository -y ppa:jacob/virtualisation
          sudo apt update
          sudo apt install qemu-user-static

      - name: build arm64 chroot
        run: |
          ./buildchroot.sh arm64

      - name: Upload binaries to release
#        if: endsWith(github.ref,'-main') 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          body: ${{ github.sha }}
          tag_name: "CHROOT-Bullseye"
          target_commitish: ${{ github.sha }}
          files: |
            debian_*.tar.gz

      - uses: actions/upload-artifact@v2
        with:
          name: bullseye-chroot
          path: |
            debian_*.tar.gz
